version: '3'

services:
    mongodb:
        image: mongo:4.0
        restart: always
        container_name: mongodb
        volumes:
            - ./mongo/data:/data/db
            - ./flights.json:/json/flights.json
            - ./users.json:/json/users.json
        ports:
            - 27017:27017
